AssetManager/Controllers/AssetsController.cs
using AssetManager.Models;
using AssetManager.Repos;
using AssetManager.Services;
using AssetManager.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AssetManager.Controllers;

[Authorize(Roles = "Admin, Basic")]
public class AssetsController : Controller
{
    private readonly IAssetService _assetService;
    private readonly IPeopleService _peopleService;
    private readonly IDictService _dictService;

    public AssetsController(IAssetRepository repository, IAssetService assetService, IPeopleService peopleService, IDictService dictService)
    {
        _assetService = assetService;
        _peopleService = peopleService;
        _dictService = dictService;
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        AssetGridViewModel vm = await _assetService.GetPageOfAssets(1);

        return View(vm);
    }

    [Authorize(Roles = "Admin")]
    [HttpGet("Assets/GetPageOfAssets/{pageNumber}")]
    public async Task<IActionResult> GetPageOfAssets(int pageNumber)
    {
        AssetGridViewModel vm = await _assetService.GetPageOfAssets(pageNumber);

        return PartialView("_GridPartial", vm);
    }

    [Authorize(Roles = "Admin, Basic")]
    [HttpGet]
    public async Task<IActionResult> MyAssets()
    {
        var personId = this.User.Claims.FirstOrDefault(c => c.Type == "PersonId")?.Value;

        if (personId == null)
        {
            return View(new List<Asset>());
        }
        else
        {
            List<Asset> list = await _assetService.GetAssetsByPersonId(int.Parse(personId));
            return View(list);
        }
    }
    
    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> AddEdit(int id)
    {
        AssetAddEditViewModel vm = new();

        vm.People = await _peopleService.GetAllPeople();
        vm.AssetTypeOptions = _dictService.GetDictItems(101);
        vm.ModelOptions = _dictService.GetDictItems(102);
        vm.SiteOptions = _dictService.GetDictItems(103);

        if (id == 0)
            return PartialView("_AddEditAssetModal", vm);
        
        try
        {
            vm.Asset = await _assetService.GetAssetById(id);
        }
        catch (ArgumentException)
        {
            return BadRequest("The Person is not valid.");
        }
            
            
        return PartialView("_AddEditAssetModal", vm);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> AddEdit(AssetAddEditViewModel vm)
    {
        int assetId;

        if(vm.Asset.AssetId == 0)
        {
            assetId = await _assetService.Create(vm.Asset);
        }
        else
        {
            await _assetService.Update(vm.Asset);

            assetId = vm.Asset.AssetId;
        }

        var asset = await _assetService.GetAssetById(assetId);

        if (asset == null)
            return BadRequest();

        return PartialView("_RowPartial", asset);
    }

    [Authorize(Roles = "Admin")]
    [HttpDelete]
    public async Task<IActionResult> Delete(int id)
    {
        await _assetService.Delete(id);

        return Ok();
    }

}

AssetManager/Controllers/OrdersController.cs
using AssetManager.Models;
using Microsoft.AspNetCore.Mvc;
using AssetManager.Services;
using AssetManager.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace AssetManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrdersController : Controller
    {

        private readonly IOrderService _orderService;
        private readonly IPeopleService _peopleService;
        private readonly IDictService _dictService;

        public OrdersController(IOrderService orderService, IPeopleService peopleService, IDictService dictService)
        {
            _orderService = orderService;
            _peopleService = peopleService;
            _dictService = dictService;
        }

        public async Task<ActionResult> Index()
        {
            return View(await _orderService.GetPageOfOrders(1));
        }

        [HttpGet("Orders/GetPageOfOrders/{pageNumber}")]
        public async Task<ActionResult> GetPageOfOrders(int pageNumber)
        {
            return PartialView("_GridPartial", await _orderService.GetPageOfOrders(pageNumber));
        }

        public async Task<ActionResult> AddEdit(int id)
        {   
            OrderAddEditViewModel vm = new()
            {
                People = await _peopleService.GetAllPeople(),
                VendorOptions = _dictService.GetDictItems(104),
                ProductOptions = _dictService.GetDictItems(102)
            };

            vm.Order.Products.Add(new ProductOrder());

            if (id == 0)
                return PartialView("_AddEditOrderModal", vm);

            vm.Order = await _orderService.GetOrderById(id);
    
            return PartialView("_AddEditOrderModal", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddEdit(OrderAddEditViewModel vm)
        {
            if (vm.Order == null) 
                return RedirectToAction(nameof(Index));

            int orderId;

            if (vm.Order.OrderId == 0)
            {
                var order = await _orderService.Create(vm.Order);

                orderId = order.OrderId;
            }
            else
            {
                await _orderService.Update(vm.Order);

                orderId = vm.Order.OrderId;
            }

            return PartialView("_RowPartial", await _orderService.GetOrderById(orderId));
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            await _orderService.Delete(id);

            return Ok();
        }

        [HttpPost]
        public async Task<ActionResult> ReceiveOrder(int id)
        {
            try
            {
                await _orderService.ReceiveOrder(id);

                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

AssetManager/Controllers/PeopleController.cs
using AssetManager.Models;
using AssetManager.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.ContentModel;

namespace AssetManager.Controllers;

[Authorize(Roles = "Admin")]
public class PeopleController : Controller
{
    private readonly IPeopleService _peopleService;
    private readonly IAssetService _assetService;

    public PeopleController(IPeopleService peopleService, IAssetService assetService)
    {
        _peopleService = peopleService;
        _assetService = assetService;
    }

    public async Task<ActionResult> Index()
    {
        return View(await _peopleService.GetPageOfPeople(1));
    }

    [HttpGet("People/GetPageOfPeople/{pageNumber}")]
    public async Task<ActionResult> GetPageOfPeople(int pageNumber)
    {
        return PartialView("_GridPartial", await _peopleService.GetPageOfPeople(pageNumber));
    }

    [HttpGet]
    public async Task<ActionResult> GetPersonOptions()
    {
        return PartialView("_PersonOptions", await _peopleService.GetAllPeople());
    }

    [HttpGet]
    public async Task<ActionResult> AddEdit(int id)
    {
        if (id == 0)
            return PartialView("_AddEditPersonModal");

        return PartialView("_AddEditPersonModal", await _peopleService.GetPersonById(id));
                   
    }

    [HttpPost] //[ValidateAntiForgeryToken]
    public async Task<ActionResult> AddEdit([Bind("PersonId,FirstName,LastName,Email")]Person person)
    {
        if (person.PersonId == 0)
        {
            person.PersonId = await _peopleService.Create(person);

            return PartialView("_RowPartial", person);
        }
        else
        {
            await _peopleService.Update(person);

            return PartialView("_RowPartial", person);
        }
    }

    [HttpDelete]
    public async Task<ActionResult> Delete(int id)
    {
        await _peopleService.Delete(id);

        return Ok();
    }

    [HttpPost]
    public async Task<ActionResult> RemoveAsset(int personId, int assetId)
    {
        await _peopleService.RemoveAssetMap(personId, assetId);

        return Ok();
    }

    [HttpPost]
    public async Task<ActionResult> MapAsset(int personId, int assetId)
    {
        try
        {
            return Ok(JsonConvert.SerializeObject(await _peopleService.MapAssetToPerson(personId, assetId)));
        }
        catch (ArgumentException ex)
        {
            return BadRequest(ex.Message);
        }
    }
}

AssetManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssetManager.styles.css" asp-append-version="true" />

    <script src="https://kit.fontawesome.com/09fbba0a4f.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 text-dark" style="padding-top: 0px;padding-bottom: 0px;">
            <div class="container-fluid">
                <div class="ms-3 d-flex align-items-center">
                    <div class="navbar-brand pe-none text-dark ps-2 mb-1" style="display:flex;align-items:center; margin-bottom: 2px;">Asset Manager</div>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Assets" asp-action="MyAssets">My Assets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="People" asp-action="Index">People</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Assets" asp-action="Index">Assets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                        </ul>
                    }
                </div>

                <partial name="_LoginPartial" />

            </div>
        </nav>

        <div id="alertDivGreen" class="alert alert-success fixed-top pt-1 pb-1 mt-2" style="z-index:9999; width:33.3%; margin-left:33.3%; display: none;"></div>
        <div id="alertDivRed" class="alert alert-danger fixed-top pt-1 pb-1 mt-2" style="z-index:9999; width:33.3%; margin-left:33.3%; display: none;"></div>
    </header>
    <div class="container" style="height:81vh;">
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted">
        <div class="container-fluid" style="font-size:.75rem">
            &copy; 2022 - Mike Warren&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/mike-warren-dev/AssetManager">GitHub</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="https://www.linkedin.com/in/michaeldouglaswarren/">LinkedIn</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>